---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.18.0
  labels:
    managed: ""
    owner: ""
  name: podnetworkinstances.multitenancy.acn.azure.com
spec:
  group: multitenancy.acn.azure.com
  names:
    kind: PodNetworkInstance
    listKind: PodNetworkInstanceList
    plural: podnetworkinstances
    shortNames:
    - pni
    singular: podnetworkinstance
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.status
      name: Status
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: PodNetworkInstance is the Schema for the PodNetworkInstances
          API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: PodNetworkInstanceSpec defines the desired state of PodNetworkInstance
            properties:
              defaultDenyACL:
                default: false
                description: DefaultDenyACL bool indicates whether default deny policy
                  will be present on the pods upon pod creation
                type: boolean
              podIPReservationSize:
                default: 0
                description: Deprecated - use PodNetworkConfigs
                type: integer
              podNetworkConfigs:
                description: |-
                  PodNetworkConfigs describes each PodNetwork to attach to a single Pod
                  optional for now in case orchestrator uses the deprecated fields
                items:
                  description: PodNetworkConfig describes a template for how to attach
                    a PodNetwork to a Pod
                  properties:
                    ipConstraint:
                      default: ""
                      description: |-
                        IPConstraint specifies criteria for selecting IP addresses from the PodNetwork's subnet.
                        Must be a valid IPv4 address or CIDR notation with /32 prefix.
                        This is an optional field.
                        Examples:
                          - IPv4 address: "192.168.0.1"
                          - IPv4 CIDR:    "192.168.0.1/32"
                      maxLength: 18
                      pattern: ^$|^((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)\.){3}(25[0-5]|(2[0-4]|1\d|[1-9]|)\d)(\/32)?$
                      type: string
                    podIPReservationSize:
                      default: 0
                      description: PodIPReservationSize is the number of IP address
                        to statically reserve
                      type: integer
                    podNetwork:
                      description: PodNetwork is the name of a PodNetwork resource
                      type: string
                  required:
                  - podNetwork
                  type: object
                  x-kubernetes-validations:
                  - message: ipConstraint can only be specified when podIPReservationSize
                      is 1
                    rule: size(self.ipConstraint) == 0 || self.podIPReservationSize
                      == 1
                type: array
              podnetwork:
                description: Deprecated - use PodNetworkConfigs
                type: string
            type: object
          status:
            description: PodNetworkInstanceStatus defines the observed state of PodNetworkInstance
            properties:
              podIPAddresses:
                items:
                  type: string
                type: array
              podNetworkStatuses:
                additionalProperties:
                  description: PNIStatus indicates the status of PNI
                  enum:
                  - Ready
                  - CreateReservationSetError
                  - PodNetworkNotReady
                  - InsufficientIPAddressesOnSubnet
                  type: string
                type: object
              status:
                description: PNIStatus indicates the status of PNI
                enum:
                - Ready
                - CreateReservationSetError
                - PodNetworkNotReady
                - InsufficientIPAddressesOnSubnet
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
